name: custom actions
on:
  push:
    branches: [main, prod]

jobs:
  testing-actions:
    runs-on: ubuntu-latest
    steps:
      - name: checkout files to vm
        uses: actions/checkout@v2.3.4

      - name: WSO2 APIMCloud CICD v1 - petstore
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: mihinduranasinghe/WSO2-APIManager-Cloud-CICD-Beta@v1.0.0
        with:
          usernameTargettedTenant: "mihindu@wso2.com@development"
          passwordTargettedTenant: ${{secrets.PASSWORD}}
          APIProjectName: "SampleStore"
          APIVersion: "1.0.0"

      - name: WSO2 APIMCloud CICD v2 - petstore
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: mihinduranasinghe/WSO2-APIManager-Cloud-CICD-Beta@v1.0.0
        with:
          usernameTargettedTenant: "mihindu@wso2.com@development"
          passwordTargettedTenant: ${{secrets.PASSWORD}}
          APIProjectName: "SampleStore"
          APIVersion: "2.0.0"

      - name: WSO2 APIMCloud CICD v1 - petstore - prod
        if: github.event_name == 'push' && github.ref == 'refs/heads/prod'
        uses: mihinduranasinghe/WSO2-APIManager-Cloud-CICD-Beta@v1.0.0
        with:
          usernameTargettedTenant: "mihindu@wso2.com@development"
          passwordTargettedTenant: ${{secrets.PASSWORD}}
          APIProjectName: "SampleStore"
          APIVersion: "1.0.0"

      - name: WSO2 APIMCloud CICD v2 - petstore - prod
        if: github.event_name == 'push' && github.ref == 'refs/heads/prod'
        uses: mihinduranasinghe/WSO2-APIManager-Cloud-CICD-Beta@v1.0.0
        with:
          usernameTargettedTenant: "mihindu@wso2.com@development"
          passwordTargettedTenant: ${{secrets.PASSWORD}}
          APIProjectName: "SampleStore"
          APIVersion: "2.0.0"
